"""initial schema gamisjumbo v1

Revision ID: e7b764ce4a01
Revises: 
Create Date: 2026-10-07 10:16:13.559599
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e7b764ce4a01'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_type', sa.Enum('boss', 'agent', 'system', name='actor_type', native_enum=False, length=30), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=True),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index('ix_activity_log_entity', ['entity_id', 'id'], unique=False)

    op.create_table('api_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=200), nullable=False),
    sa.Column('owner_actor', sa.String(length=20), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_token_token_hash'), ['token_hash'], unique=True)

    op.create_table('idempotency_key',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('notification_outbox',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pilar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('warna', sa.String(length=20), nullable=False),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('kuota_persen', sa.Integer(), nullable=False),
    sa.Column('kuota_mingguan', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('caption_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('pilar_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pilar_id'], ['pilar.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('judul_hook', sa.String(length=200), nullable=False),
    sa.Column('hook_norm', sa.String(length=190), nullable=True),
    sa.Column('pilar_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('quote', 'mini_story', 'doa', 'meme_relatable', 'question', 'carousel', 'reels', 'text', name='format', native_enum=False, length=30), nullable=False),
    sa.Column('kanal', sa.Enum('fb_feed', 'fb_reels', 'fb_story', name='kanal', native_enum=False, length=30), nullable=False),
    sa.Column('naskah_md', sa.Text(), nullable=False),
    sa.Column('caption_fb', sa.Text(), nullable=True),
    sa.Column('cta', sa.Enum('komentar', 'share', 'save', 'follow', 'tanpa_cta', name='cta', native_enum=False, length=30), nullable=False),
    sa.Column('hashtags', sa.String(length=300), nullable=True),
    sa.Column('visual_note', sa.Text(), nullable=True),
    sa.Column('sumber_dalil', sa.String(length=300), nullable=True),
    sa.Column('fact_level', sa.Integer(), nullable=False),
    sa.Column('verifikator', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ide', 'draft', 'review', 'ditolak', 'siap_tayang', 'terjadwal', 'tayang', 'arsip', name='content_status', native_enum=False, length=30), nullable=False),
    sa.Column('source', sa.Enum('agent_auto', 'agent_brief', 'boss_manual', name='source', native_enum=False, length=30), nullable=False),
    sa.Column('owner_token_id', sa.Integer(), nullable=True),
    sa.Column('request_ref', sa.String(length=300), nullable=True),
    sa.Column('usulan_jadwal', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.String(length=500), nullable=True),
    sa.Column('jadwal_tayang', sa.Date(), nullable=True),
    sa.Column('slot_waktu', sa.Enum('pagi', 'malam', name='slot_waktu', native_enum=False, length=30), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('tayang_at', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('platform_post_id', sa.String(length=100), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('link_posting', sa.String(length=300), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.Column('diubah', sa.DateTime(), nullable=True),
    sa.CheckConstraint('fact_level BETWEEN 1 AND 4', name='ck_content_fact_level'),
    sa.ForeignKeyConstraint(['owner_token_id'], ['api_token.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pilar_id'], ['pilar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_item_hook_norm'), ['hook_norm'], unique=False)
        batch_op.create_index('ix_content_owner_status', ['owner_token_id', 'status'], unique=False)
        batch_op.create_index('ix_content_status_pilar_tayang', ['status', 'pilar_id', 'tayang_at'], unique=False)

    op.create_table('asset',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('jenis', sa.String(length=20), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('alt', sa.String(length=200), nullable=True),
    sa.Column('urutan', sa.Integer(), nullable=False),
    sa.Column('ukuran', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_token_id', sa.Integer(), nullable=True),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_revision',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('versi', sa.Integer(), nullable=False),
    sa.Column('naskah_md', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('actor_type', sa.Enum('boss', 'agent', 'system', name='actor_type', native_enum=False, length=30), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'versi', name='uq_revisi_versi')
    )
    op.create_table('hook_registry',
    sa.Column('hook_norm', sa.String(length=190), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('asal', sa.Enum('seed', 'konten', name='hook_asal', native_enum=False, length=30), nullable=False),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_item.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('hook_norm')
    )
    op.create_table('metric_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('capture_date', sa.Date(), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('komen', sa.Integer(), nullable=False),
    sa.Column('share', sa.Integer(), nullable=False),
    sa.Column('dibuat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'capture_date', name='uq_metrik_harian')
    )
    op.create_table('production_checklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('butir', sa.String(length=255), nullable=False),
    sa.Column('tercentang', sa.Boolean(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('diubah', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['content_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'butir', name='uq_checklist_butir')
    )
    op.create_table('schedule_slot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('slot_waktu', sa.Enum('pagi', 'malam', name='slot_waktu', native_enum=False, length=30), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=True),
    sa.Column('status_slot', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content_item.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tanggal', 'platform', 'slot_waktu', name='uq_slot_harian')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_slot')
    op.drop_table('production_checklist')
    op.drop_table('metric_snapshot')
    op.drop_table('hook_registry')
    op.drop_table('content_revision')
    op.drop_table('asset')
    with op.batch_alter_table('content_item', schema=None) as batch_op:
        batch_op.drop_index('ix_content_status_pilar_tayang')
        batch_op.drop_index('ix_content_owner_status')
        batch_op.drop_index(batch_op.f('ix_content_item_hook_norm'))

    op.drop_table('content_item')
    op.drop_table('caption_template')
    op.drop_table('user')
    op.drop_table('pilar')
    op.drop_table('notification_outbox')
    op.drop_table('idempotency_key')
    with op.batch_alter_table('api_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_token_token_hash'))

    op.drop_table('api_token')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_log_entity')

    op.drop_table('activity_log')
    # ### end Alembic commands ###
